import classnames from "classnames";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: {
  children: React.ReactNode;
  analytics: React.ReactNode;
}) {
  // throw new Error("Not implemented");

  return (
    <html lang="en">
      <body
        className={classnames(inter.className, "min-h-screen flex flex-col")}
      >
        <header className="flex justify-between p-5 border-b border-gray-600">
          <div>Next App</div>
          <nav>
            <ul className="flex gap-4">
              <li>
                <Link href="/">Home</Link>
              </li>
            </ul>
          </nav>
        </header>
        <main className="flex flex-col items-center justify-between p-24 flex-1">
          {props.children}
          {props.analytics}
        </main>
        <footer className="p-5 border-t border-gray-600">
          Created by Luis
        </footer>
      </body>
    </html>
  );
}
